from typing import Union, TypeAlias

import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.preprocessing import PolynomialFeatures

from ..base import BaseObservable


class IdentityObservable(BaseObservable):
    def __init__(self):
        super().__init__()
        self.n_features_in_ = None 
        
    def fit(self, X, y=None):
        self.n_features_in_ = X.shape[1]
        return self
    
    def transform(self, X):
        return X
    
    def get_output_names(self) -> list[str]:
        if self.n_features_in_ is None:
            raise RuntimeError("IdentityObservable must be fitted before calling get_output_names")
            
        return [f"x{i}" for i in range(self.n_features_in_)]
    

class PolynomialObservable(BaseObservable):
    def __init__(self, degree: int = 2, interaction_only: bool = False, include_bias: bool = False):
        super().__init__()
        self.degree = degree
        self.interaction_only = interaction_only
        self.include_bias = include_bias
        
        self.poly_transformer_ = None
        self.n_input_features_ = None

    def fit(self, X, y=None):
        """Fit the PolynomialFeatures transformer."""
        self.poly_transformer_ = PolynomialFeatures(
            degree=self.degree, 
            include_bias=self.include_bias, 
            interaction_only=self.interaction_only
        )
        self.poly_transformer_.fit(X)
        
        self.n_input_features_ = X.shape[1]
        return self

    def transform(self, X):
        """Transform the data X using the fitted transformer."""
        if self.poly_transformer_ is None:
            raise RuntimeError("PolynomialObservable must be fitted before calling transform.")
        
        return self.poly_transformer_.transform(X)

    def get_output_names(self) -> list[str]:
        """Return the feature names generated by PolynomialFeatures."""
        if self.poly_transformer_ is None:
            raise RuntimeError("PolynomialObservable must be fitted before calling get_output_names.")
        input_names = [f"x{i}" for i in range(self.n_input_features_)]
        
        return self.poly_transformer_.get_feature_names_out(input_names).tolist()


class RBFObservable(BaseObservable):
    def __init__(self, n_centers: int = 10, gamma: float = 1.0, random_state: int = 42):
        super().__init__()
        self.n_centers = n_centers
        self.gamma = gamma
        self.random_state = random_state
        self.centers_ = None

    def fit(self, X, y=None):
        kmeans = KMeans(n_clusters=self.n_centers, random_state=self.random_state)
        kmeans.fit(X)
        self.centers_ = kmeans.cluster_centers_
        return self

    def transform(self, X):
        if self.centers_ is None:
            raise RuntimeError("RBFObservable must be fitted first.")
        return rbf_kernel(X, self.centers_, gamma=self.gamma)

    def get_output_names(self) -> list[str]:
        return [f"rbf_{i}" for i in range(self.n_centers)]


class TrigonometricObservable(BaseObservable):
    def __init__(self, frequencies: list[float] = [1.0]):
        super().__init__()
        self.frequencies = frequencies
        self.n_input_features_ = None

    def fit(self, X, y=None):
        self.n_input_features_ = X.shape[1]
        return self

    def transform(self, X):
        features = []
        for freq in self.frequencies:
            features.append(np.sin(freq * X))
            features.append(np.cos(freq * X))
        return np.hstack(features)

    def get_output_names(self) -> list[str]:
        names = []
        for freq in self.frequencies:
            for i in range(self.n_input_features_):
                names.append(f"sin({freq}x{i})")
            for i in range(self.n_input_features_):
                names.append(f"cos({freq}x{i})")
        return names
    

class CombinedObservable(BaseObservable):
    def __init__(self, observables: list[BaseObservable]):
        super().__init__()
        self.observables = observables

    def fit(self, X, y=None):
        for obs in self.observables:
            obs.fit(X, y)
        return self

    def transform(self, X):
        feature_list = [obs.transform(X) for obs in self.observables]
        return np.hstack(feature_list)

    def get_output_names(self) -> list[str]:
        names = []
        for obs in self.observables:
            names.extend(obs.get_output_names())
        return names